### ISSUE TITLE
Problem configuring GATE from git clone: Waf: The wscript in '../GATE/thirdParty/bgen' is unreadable

### ISSUE THREAD

**Issue by rsalomonupenn** [weizhou0/GATE#14]
( note I'm manually redacting part of the path, for security purposes)
Successfully installed xiaoyeli/superlu
Waf: The wscript in '../GATE/thirdParty/bgen' is unreadable
Traceback (most recent call last):
  File "../GATE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Scripting.py", line 101, in waf_entry_point
    set_main_module(os.path.normpath(os.path.join(Context.run_dir,Context.WSCRIPT_FILE)))
  File "../GATE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Scripting.py", line 141, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "../GATE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Context.py", line 360, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "../GATE/thirdParty/bgen/wscript", line 33
        print "Creating %s build..." % bld.options.mode
              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Creating %s build..." % bld.options.mode)?

**Comment by rsalomonupenn** [comment]
Ok I tried with python 2.7.14, and may have finally received an error that reveals a different concrete problem!

FIPS!

We have FIPS enabled on our systems, and so I see this error:

ValueError: error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips

**Comment by rsalomonupenn** [comment]
Closing this, see #16 instead
